spring.application.name=MediCare
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=changemeinprod!
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.mvc.format.date=dd/MM/yyyy

jwt.secret-key=bbec1617b404b098ddf7cfecaefb3d036667dcdd1fdbdf7491fb062185a8efe2
jwt.expiration=300000
jwt.refresh-token.expiration=604800000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=abir.belkaroui@gmail.com
spring.mail.password=desf wepy cxtn bvhi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
activation.url=http://localhost:4200/activation_account