spring.application.name=MediCare
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=changemeinprod!
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.adjust-dates-to-context-time-zone=true
spring.jackson.datatype.jsr310.serializer.write-dates-as-timestamps=false



jwt.secret-key=bbec1617b404b098ddf7cfecaefb3d036667dcdd1fdbdf7491fb062185a8efe2
jwt.expiration=86400000
jwt.refresh-token.expiration=604800000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=abir.belkaroui@gmail.com
spring.mail.password=desf wepy cxtn bvhi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
activation.url=http://localhost:4200/activation_account

cloudinary.cloud_name=dprfvo7c4
cloudinary.api_key=215856294514827
cloudinary.api_secret=-H4Xz167jt6JHeHUo-EYSYab-8o
graphql.servlet.mapping=/graphql
graphql.graphiql.enabled=true
graphql.service.url=https://api-bdpm-graphql.axel-op.fr/graphql"
app.firebase-configuration-file=medicare-notif-firebase-adminsdk-fbsvc-3e79e3c468.json